version: '3.3' 

volumes:
  postgres_data:
  static:

services: 
  frontend: 
    image: luppiters/foodgram_frontend 
    volumes: 
      - ../frontend/result_build:/usr/share/nginx/html/

  backend:
    image: luppiters/foodgram_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static:/app/collected_static
      - ./backend/media:/app/media
    env_file: 
      - ./.env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  nginx: 
    image: nginx:1.19.3 
    ports: 
      - "8888:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
      - ../frontend/result_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/ 
      - static:/app/collected_static
      - ./backend/media:/app/media
    depends_on:
      - frontend
      - backend

